services:
  - type: web
    name: rt-ranking-endurance-api
    runtime: node
    rootDir: api
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    branch: "main"
    autoDeployTrigger: "commit"
    buildFilter:
      paths:
        - api/**/*
        - data/*.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://rt-ranking-endurance.onrender.com

  - type: web
    runtime: static
    name: rt-ranking-endurance
    rootDir: static
    staticPublishPath: .
    branch: "main"
    autoDeployTrigger: "commit"
    buildFilter:
      paths:
        - static/**/*
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
